repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4  # Use the latest version
    hooks:
      - id: flake8
        additional_dependencies: [pep8-naming]
        args: [--max-line-length=120]
